### ISSUE TITLE
No nms_cuda.c in lib/model/nms/src

### ISSUE THREAD

**Issue by rnjtsh** [kentaroy47/training-domain-specific-models#2]
While executing `sh make.sh`, I get following error as file is missing.

gcc: error: /ssd_scratch/cvit/ranajit.saha/training-domain-specific-models/lib/model/nms/src/nms_cuda.c: No such file or directory

Is this the same file as provided by [jwyang/faster-rcnn.pytorch](https://github.com/jwyang/faster-rcnn.pytorch)?

**Comment by kentaroy47** [comment]
Thanks for pointing this out.
somehow nms_cuda.c was left out.

I added nms_cuda.c, which is the same file as 
jwyang/faster-rcnn.pytorch
